# Generated by Django 5.0.6 on 2026-09-09 05:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('facility_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('facility_type', models.CharField(choices=[('GENERAL_HOSPITAL', 'Tertiary General Hospital'), ('SPECIALTY_CLINIC', 'Specialty Medical Clinic'), ('AMBULATORY_CENTER', 'Ambulatory Surgery Center'), ('URGENT_CARE', 'Urgent Care Facility'), ('DIAGNOSTIC_LAB', 'Diagnostic & Pathology Center'), ('COMMUNITY_HEALTH', 'Community Health Clinic')], default='GENERAL_HOSPITAL', max_length=32)),
                ('license_number', models.CharField(max_length=128, unique=True)),
                ('accreditation_body', models.CharField(default='Joint Commission / State DOH', max_length=128)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('npi_number', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_services_available', models.BooleanField(default=True)),
                ('trauma_level', models.CharField(choices=[('LEVEL_1', 'Level I Trauma'), ('LEVEL_2', 'Level II Trauma'), ('LEVEL_3', 'Level III Trauma'), ('NONE', 'Non-Trauma Facility')], default='LEVEL_1', max_length=32)),
                ('total_capacity', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Healthcare Facility',
                'verbose_name_plural': 'Healthcare Facilities',
                'db_table': 'hs_facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('CLINICAL', 'Clinical Specialty'), ('DIAGNOSTIC', 'Diagnostic & Laboratory'), ('SURGICAL', 'Surgery & Operation Theater'), ('EMERGENCY', 'Emergency & Critical Care'), ('ADMINISTRATIVE', 'Administrative & Support'), ('PHARMACY', 'Pharmacy & Therapeutics')], default='CLINICAL', max_length=32)),
                ('head_of_department', models.CharField(blank=True, max_length=255)),
                ('contact_extension', models.CharField(blank=True, max_length=16)),
                ('floor_number', models.CharField(default='1', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='facilities.facility')),
            ],
            options={
                'db_table': 'hs_facility_departments',
                'ordering': ['facility', 'name'],
                'unique_together': {('facility', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FacilityHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('emergency_only', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='facilities.facility')),
            ],
            options={
                'db_table': 'hs_facility_holidays',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('NICU', 'Neonatal Intensive Care Unit'), ('GENERAL_MALE', 'General Male Ward'), ('GENERAL_FEMALE', 'General Female Ward'), ('PEDIATRIC', 'Pediatric Ward'), ('MATERNITY', 'Maternity & Labor'), ('POST_OP', 'Post-Operative Recovery'), ('ISOLATION', 'Infection Isolation Ward')], default='GENERAL_MALE', max_length=32)),
                ('floor', models.CharField(default='2', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='facilities.department')),
            ],
            options={
                'db_table': 'hs_facility_wards',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=32)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('has_oxygen_supply', models.BooleanField(default=True)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='facilities.ward')),
            ],
            options={
                'db_table': 'hs_facility_rooms',
                'unique_together': {('ward', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='20:00:00')),
                ('is_24_hours', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='facilities.facility')),
            ],
            options={
                'db_table': 'hs_facility_operating_hours',
                'unique_together': {('facility', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_identifier', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Clean'), ('OCCUPIED', 'Patient Occupied'), ('CLEANING', 'Housekeeping / Sanitation'), ('MAINTENANCE', 'Biomedical Maintenance'), ('RESERVED', 'Reserved for Admission')], db_index=True, default='AVAILABLE', max_length=32)),
                ('is_electric_adjustable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_cleaned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='facilities.room')),
            ],
            options={
                'db_table': 'hs_facility_beds',
                'unique_together': {('room', 'bed_identifier')},
            },
        ),
    ]
