# Generated by Django 5.0.6 on 2026-09-09 05:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10DiagnosisCode',
            fields=[
                ('code', models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(db_index=True, max_length=512)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('chapter_title', models.CharField(max_length=255)),
                ('category_code', models.CharField(db_index=True, max_length=16)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_chronic', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hs_icd10_diagnosis_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('encounter_class', models.CharField(choices=[('AMBULATORY', 'Outpatient Ambulatory Visit'), ('EMERGENCY', 'Emergency Department Visit'), ('INPATIENT', 'Inpatient Hospital Admission'), ('TELEMEDICINE', 'Virtual Telemedicine Encounter'), ('HOME_HEALTH', 'Home Health Care Visit')], default='AMBULATORY', max_length=32)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned / Scheduled'), ('ARRIVED', 'Patient Arrived'), ('IN_PROGRESS', 'Clinical Consultation Active'), ('ON_HOLD', 'On Hold (Pending Diagnostics)'), ('FINISHED', 'Encounter Signed & Closed'), ('CANCELLED', 'Encounter Cancelled')], db_index=True, default='IN_PROGRESS', max_length=32)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('discharge_disposition', models.CharField(blank=True, choices=[('ROUTINE', 'Discharged to Home / Routine'), ('ADMIT', 'Admitted to Inpatient Ward'), ('TRANSFER', 'Transferred to Tertiary Center'), ('AMA', 'Left Against Medical Advice'), ('EXPIRED', 'Patient Expired')], max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='doctors.doctorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_clinical_encounters',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('XRAY', 'X-Ray Radiograph'), ('MRI', 'Magnetic Resonance Imaging (MRI)'), ('CT_SCAN', 'Computed Tomography (CT)'), ('ULTRASOUND', 'Ultrasound Sonogram'), ('ECG', 'Electrocardiogram (ECG/EKG)'), ('LAB_SCAN', 'Scanned Laboratory Report'), ('PATHOLOGY', 'Histopathology Slide Image'), ('DISCHARGE_DOC', 'Discharge Summary Document')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='clinical_attachments/%Y/%m/')),
                ('mime_type', models.CharField(default='application/pdf', max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinical_records.encounter')),
            ],
            options={
                'db_table': 'hs_clinical_attachments',
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Primary / Principal Diagnosis'), ('SECONDARY', 'Secondary Comorbidity'), ('DIFFERENTIAL', 'Differential Working Diagnosis'), ('DISCHARGE', 'Final Discharge Diagnosis')], default='PRIMARY', max_length=32)),
                ('clinical_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical_records.encounter')),
                ('icd10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_diagnoses', to='clinical_records.icd10diagnosiscode')),
            ],
            options={
                'db_table': 'hs_encounter_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(help_text='Chief complaint, HPI, review of systems, patient-reported symptoms.')),
                ('objective', models.TextField(help_text='Physical exam findings, clinical observations, physical inspection.')),
                ('assessment', models.TextField(help_text='Clinical synthesis, diagnostic impressions, disease staging.')),
                ('plan', models.TextField(help_text='Management plan, e-prescriptions, diagnostic orders, lifestyle advisories.')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='clinical_records.encounter')),
            ],
            options={
                'db_table': 'hs_clinical_soap_notes',
            },
        ),
    ]
