# Generated by Django 5.0.6 on 2026-09-09 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Physician Consultation'), ('DIAGNOSTIC_LAB', 'Clinical Laboratory Test'), ('RADIOLOGY', 'Radiology / Diagnostic Imaging'), ('SURGICAL_PROCEDURE', 'Surgical / Minor Procedure'), ('ROOM_BOARD', 'Inpatient Room & Bed Accommodation'), ('PHARMACY', 'Medication & Biological Supplies'), ('EMERGENCY_FEE', 'Emergency Resuscitation & Triage Fee')], default='CONSULTATION', max_length=32)),
                ('base_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hs_billing_fee_schedules',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Pending Finalization'), ('ISSUED', 'Issued to Patient / Payor'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid / Settled'), ('VOID', 'Voided / Cancelled')], db_index=True, default='ISSUED', max_length=32)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clinical_records.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_billing_invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.feeschedule')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'db_table': 'hs_billing_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='PatientLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CHARGE', 'Debit / Patient Charge'), ('PAYMENT', 'Credit / Payment Received'), ('INSURANCE_CREDIT', 'Credit / Insurance Adjudication'), ('ADJUSTMENT', 'Administrative Waiver / Adjustment')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_billing_patient_ledger',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash Currency'), ('CREDIT_CARD', 'Credit / Debit Card'), ('INSURANCE_COPAY', 'Insurance Co-payment'), ('BANK_TRANSFER', 'Electronic Bank Wire (ACH)'), ('CHECK', 'Paper Check')], default='CREDIT_CARD', max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('received_by', models.CharField(default='Cashier Desk', max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'db_table': 'hs_billing_payments',
            },
        ),
    ]
