# Generated by Django 5.0.6 on 2026-09-09 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('payor_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('payor_type', models.CharField(choices=[('COMMERCIAL', 'Commercial Private Insurer'), ('MEDICARE', 'Federal Medicare (Part A/B/C/D)'), ('MEDICAID', 'State Medicaid Program'), ('TRICARE', 'Military & Veteran Health')], default='COMMERCIAL', max_length=32)),
                ('claims_email', models.EmailField(max_length=254)),
                ('claims_phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hs_insurance_providers',
            },
        ),
        migrations.CreateModel(
            name='PatientInsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(db_index=True, max_length=64)),
                ('group_number', models.CharField(blank=True, max_length=64)),
                ('copay_amount', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('coinsurance_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('annual_deductible', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField()),
                ('is_primary', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patientprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insuranceprovider')),
            ],
            options={
                'db_table': 'hs_patient_insurance_policies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('copay_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Claim'), ('SUBMITTED', 'Submitted via EDI 837'), ('UNDER_REVIEW', 'Payor Medical Review'), ('APPROVED', 'Approved for Payment'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DENIED', 'Claim Denied'), ('PAID', 'Remittance Paid (EDI 835)')], db_index=True, default='DRAFT', max_length=32)),
                ('primary_diagnosis_code', models.CharField(help_text='ICD-10 code', max_length=16)),
                ('adjudication_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('adjudicated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='billing.invoice')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.patientinsurancepolicy')),
            ],
            options={
                'db_table': 'hs_insurance_claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
