# Generated by Django 5.0.6 on 2026-09-09 05:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loinc_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hematology & Coagulation'), ('BIOCHEMISTRY', 'Clinical Biochemistry'), ('IMMUNOLOGY', 'Immunology & Serology'), ('MICROBIOLOGY', 'Microbiology & Culture'), ('URINALYSIS', 'Urinalysis & Body Fluids'), ('ENDOCRINOLOGY', 'Endocrinology & Hormones'), ('TOXICOLOGY', 'Toxicology & Drug Screens')], default='BIOCHEMISTRY', max_length=32)),
                ('measurement_unit', models.CharField(help_text='e.g. mg/dL, mmol/L, g/dL, 10^3/uL', max_length=32)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('turnaround_time_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hs_lab_test_catalog',
                'ordering': ['category', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('container_type', models.CharField(help_text='e.g. Lavender Top (EDTA), Red Top (Serum), Sterile Cup', max_length=100)),
                ('handling_instructions', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hs_lab_specimen_types',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine Outpatient'), ('URGENT', 'Urgent Clinical Priority'), ('STAT', 'Emergency STAT Immediate')], default='ROUTINE', max_length=16)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('COLLECTED', 'Specimen Collected'), ('PROCESSING', 'In Analyzer Processing'), ('COMPLETED', 'Verified & Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', max_length=32)),
                ('clinical_indication', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='clinical_records.encounter')),
                ('ordering_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_lab_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('observed_text_value', models.CharField(blank=True, max_length=255)),
                ('flag', models.CharField(choices=[('NORMAL', 'Normal Value'), ('HIGH', 'Abnormally Elevated'), ('LOW', 'Abnormally Decreased'), ('CRITICAL_HIGH', 'Panic / Critical High Alert'), ('CRITICAL_LOW', 'Panic / Critical Low Alert')], default='NORMAL', max_length=32)),
                ('reference_range_used', models.CharField(blank=True, max_length=128)),
                ('technician_notes', models.CharField(blank=True, max_length=255)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labtestcatalog')),
            ],
            options={
                'db_table': 'hs_lab_result_items',
            },
        ),
        migrations.CreateModel(
            name='DemographicReferenceRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('ALL', 'All Genders'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=16)),
                ('min_age_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('max_age_years', models.DecimalField(decimal_places=1, default=120.0, max_digits=4)),
                ('normal_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('normal_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='laboratory.labtestcatalog')),
            ],
            options={
                'db_table': 'hs_lab_reference_ranges',
            },
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='specimen_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='laboratory.specimentype'),
        ),
        migrations.CreateModel(
            name='LabSpecimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_by', models.CharField(default='Phlebotomy Staff', max_length=255)),
                ('storage_temperature', models.CharField(default='Refrigerated (2-8°C)', max_length=32)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='laboratory.laborder')),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.specimentype')),
            ],
            options={
                'db_table': 'hs_lab_specimens',
            },
        ),
    ]
