# Generated by Django 5.0.6 on 2026-09-09 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rx_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Prescription'), ('SIGNED', 'Signed & Issued by Physician'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Fully Dispensed by Pharmacy'), ('CANCELLED', 'Cancelled / Discontinued')], db_index=True, default='SIGNED', max_length=32)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField()),
                ('clinical_instructions', models.TextField(blank=True)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctorprofile')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinical_records.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(db_index=True, max_length=255)),
                ('dosage', models.CharField(help_text='e.g. 500 mg, 10 ml', max_length=64)),
                ('route', models.CharField(choices=[('ORAL', 'Oral (PO)'), ('IV', 'Intravenous (IV)'), ('IM', 'Intramuscular (IM)'), ('SC', 'Subcutaneous (SC)'), ('TOPICAL', 'Topical (Skin)'), ('INHALATION', 'Inhalation (Nebulizer/Inhaler)'), ('OPHTHALMIC', 'Ophthalmic (Eye Drops)'), ('OTIC', 'Otic (Ear Drops)')], default='ORAL', max_length=32)),
                ('frequency', models.CharField(choices=[('QD', 'Once Daily (QD)'), ('BID', 'Twice Daily (BID)'), ('TID', 'Three Times Daily (TID)'), ('QID', 'Four Times Daily (QID)'), ('PRN', 'As Needed (PRN)'), ('Q4H', 'Every 4 Hours'), ('Q6H', 'Every 6 Hours'), ('Q8H', 'Every 8 Hours'), ('STAT', 'Immediately (Single Dose)')], default='BID', max_length=32)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('quantity', models.PositiveIntegerField(default=14, help_text='Total units to dispense')),
                ('refills_allowed', models.PositiveIntegerField(default=0)),
                ('special_instructions', models.CharField(blank=True, help_text='e.g. Take with food', max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'hs_prescription_items',
            },
        ),
    ]
