# Generated by Django 5.0.6 on 2026-09-09 05:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNK', 'Unknown')], default='UNK', max_length=8)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=16)),
                ('primary_language', models.CharField(default='English', max_length=64)),
                ('is_organ_donor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hs_patient_profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(blank=True, max_length=32)),
                ('diagnosed_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Chronic Condition'), ('IN_REMISSION', 'In Remission'), ('RESOLVED', 'Resolved Historical Event')], default='ACTIVE', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_medical_history',
            },
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_relationship', models.CharField(max_length=64)),
                ('condition_name', models.CharField(max_length=255)),
                ('age_at_onset', models.PositiveIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_family_history',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('GUARDIAN', 'Legal Guardian'), ('FRIEND', 'Friend')], max_length=64)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(choices=[('MEDICATION', 'Medication / Pharmacology'), ('FOOD', 'Food Allergen'), ('ENVIRONMENTAL', 'Environmental / Seasonal'), ('BIOLOGICAL', 'Latex / Biological Product')], default='MEDICATION', max_length=32)),
                ('severity', models.CharField(choices=[('MILD', 'Mild (Rash, Itching)'), ('MODERATE', 'Moderate (Hives, Facial Swelling)'), ('SEVERE', 'Severe Anaphylaxis (Airway Compromise)')], default='MODERATE', max_length=32)),
                ('reaction_description', models.TextField()),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_allergies',
            },
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('surgery_year', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('complications', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_history', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_surgical_history',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.PositiveIntegerField(help_text='mmHg')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='mmHg')),
                ('heart_rate', models.PositiveIntegerField(help_text='beats per minute')),
                ('respiratory_rate', models.PositiveIntegerField(default=16, help_text='breaths per minute')),
                ('temperature_celsius', models.DecimalField(decimal_places=1, default=37.0, max_digits=4)),
                ('spo2_percentage', models.PositiveIntegerField(default=98, help_text='SpO2 percentage (0-100)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_patient_vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
