# Generated by Django 5.0.6 on 2026-09-09 05:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('READ', 'Record Accessed / Viewed'), ('UPDATE', 'Record Modified'), ('DELETE', 'Record Deleted'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Authentication Attempt'), ('EXPORT', 'PHI Data Exported'), ('DISPENSE', 'Medication Dispensed'), ('OVERRIDE', 'Clinical Alert Overridden')], db_index=True, max_length=32)),
                ('target_model', models.CharField(db_index=True, max_length=128)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('description', models.TextField()),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('integrity_hash', models.CharField(db_index=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hs_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
