# Generated by Django 5.0.6 on 2026-09-09 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=64)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField(default=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hs_pharmacy_batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('atc_code', models.CharField(db_index=True, help_text='WHO Anatomical Therapeutic Chemical code', max_length=16)),
                ('drug_class', models.CharField(max_length=128)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Oral Liquid / Syrup'), ('INJECTION', 'Injectable Solution'), ('OINTMENT', 'Topical Ointment / Cream'), ('INHALER', 'Metered Dose Inhaler'), ('SUPPOSITORY', 'Suppository'), ('DROPS', 'Ophthalmic / Otic Drops')], default='TABLET', max_length=32)),
                ('strength', models.CharField(help_text='e.g. 500mg, 10mg/ml', max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('is_controlled', models.BooleanField(default=False)),
                ('is_antibiotic', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('black_box_warning', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hs_pharmacy_medications',
                'ordering': ['generic_name', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='DispensationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rx_item_id', models.UUIDField(blank=True, null=True)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('dispensed_by', models.CharField(default='Staff Pharmacist', max_length=255)),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_counseling_completed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='pharmacy.batchinventory')),
            ],
            options={
                'db_table': 'hs_pharmacy_dispensations',
            },
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medication'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_adjusted', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('reason', models.CharField(choices=[('REPLENISHMENT', 'Supplier Purchase Restock'), ('EXPIRED', 'Expired Product Disposal'), ('DAMAGED', 'Damaged / Broken Packaging'), ('INVENTORY_AUDIT', 'Physical Inventory Audit Adjustment'), ('RECALL', 'FDA / Manufacturer Product Recall')], max_length=32)),
                ('performed_by', models.CharField(max_length=255)),
                ('adjusted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_order_number', models.CharField(blank=True, max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pharmacy.batchinventory')),
            ],
            options={
                'db_table': 'hs_pharmacy_adjustments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchinventory',
            unique_together={('medication', 'batch_number')},
        ),
    ]
