# Generated by Django 5.0.6 on 2026-09-09 05:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalKPIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('total_admissions', models.PositiveIntegerField(default=0)),
                ('total_discharges', models.PositiveIntegerField(default=0)),
                ('bed_occupancy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_length_of_stay_days', models.DecimalField(decimal_places=1, default=3.5, max_digits=4)),
                ('emergency_wait_time_minutes', models.PositiveIntegerField(default=22)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('claim_denial_rate', models.DecimalField(decimal_places=2, default=2.1, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hs_analytics_kpi_reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
