# Generated by Django 5.0.6 on 2026-09-09 05:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('board_name', models.CharField(default='American Board of Medical Specialties', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'db_table': 'hs_medical_specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npi_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('licensing_state', models.CharField(default='New York', max_length=64)),
                ('license_expiry_date', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField(default=5)),
                ('default_consultation_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('biography', models.TextField(blank=True)),
                ('is_telehealth_enabled', models.BooleanField(default=True)),
                ('is_accepting_new_patients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hs_doctor_profiles',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Medical Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'hs_doctor_leaves',
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=128)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'hs_doctor_qualifications',
            },
        ),
        migrations.CreateModel(
            name='DoctorFeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('IN_PERSON_GENERAL', 'In-Person General Consultation'), ('IN_PERSON_FOLLOWUP', 'In-Person Follow-up'), ('TELEHEALTH', 'Telehealth Video Consultation'), ('EMERGENCY_ON_CALL', 'Emergency On-Call Consultation')], default='IN_PERSON_GENERAL', max_length=32)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_fees', to='facilities.facility')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'hs_doctor_fee_schedules',
                'unique_together': {('doctor', 'facility', 'consultation_type')},
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('max_patients_per_slot', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='facilities.facility')),
            ],
            options={
                'db_table': 'hs_doctor_schedules',
                'unique_together': {('doctor', 'facility', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='doctors.doctorprofile')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.specialty')),
            ],
            options={
                'db_table': 'hs_doctor_specialty_mappings',
                'unique_together': {('doctor', 'specialty')},
            },
        ),
    ]
