# Generated by Django 5.0.6 on 2026-09-09 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('scheduled_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('consultation_type', models.CharField(choices=[('GENERAL', 'General Outpatient Consultation'), ('FOLLOW_UP', 'Post-Treatment Follow-up'), ('TELEHEALTH', 'Virtual Telehealth Video Consultation'), ('SPECIALIST', 'Specialist Consultation'), ('URGENT', 'Urgent Walk-in Care')], default='GENERAL', max_length=32)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Confirmed & Scheduled'), ('CHECKED_IN', 'Patient Checked In / Waiting Room'), ('IN_CONSULTATION', 'In Consultation with Doctor'), ('COMPLETED', 'Consultation Completed'), ('CANCELLED', 'Cancelled by Patient or Clinic'), ('RESCHEDULED', 'Rescheduled to Another Slot'), ('NO_SHOW', 'Patient Did Not Attend')], db_index=True, default='SCHEDULED', max_length=32)),
                ('chief_complaint', models.TextField()),
                ('cancellation_reason', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_appointments',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('is_served', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='appointments.appointment')),
            ],
            options={
                'db_table': 'hs_queue_tickets',
            },
        ),
    ]
