# Generated by Django 5.0.6 on 2026-09-09 05:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInferenceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=64)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(default=dict)),
                ('is_overridden', models.BooleanField(default=False)),
                ('doctor_override_reason', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hs_ai_inference_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRiskScoreLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_name', models.CharField(help_text='e.g. Framingham 10-Year ASCVD, Glasgow-Blatchford', max_length=64)),
                ('calculated_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('risk_category', models.CharField(choices=[('LOW', 'Low Clinical Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Clinical Risk'), ('VERY_HIGH', 'Critical / Very High Risk')], default='LOW', max_length=32)),
                ('explanation', models.TextField()),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_ai_risk_score_logs',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalTriageAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presenting_complaint', models.CharField(max_length=255)),
                ('urgency_level', models.IntegerField(choices=[(1, 'Level 1: Immediate Resuscitation (Red)'), (2, 'Level 2: Very Urgent / Emergent (Orange)'), (3, 'Level 3: Urgent (Yellow)'), (4, 'Level 4: Standard / Less Urgent (Green)'), (5, 'Level 5: Non-Urgent (Blue)')], db_index=True, default=3)),
                ('discriminator_flags', models.JSONField(default=list, help_text='Clinical red flags observed')),
                ('pain_score', models.PositiveIntegerField(default=0, help_text='Pain scale 0-10')),
                ('recommended_disposition', models.CharField(max_length=255)),
                ('assessed_by', models.CharField(default='Triage Assessment Engine', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to='clinical_records.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hs_ai_triage_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteractionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_a', models.CharField(db_index=True, max_length=150)),
                ('drug_b', models.CharField(db_index=True, max_length=150)),
                ('severity', models.CharField(choices=[('CONTRAINDICATED', 'Strictly Contraindicated (Severe Harm / Fatal)'), ('MAJOR', 'Major Interaction (Requires Doctor Override)'), ('MODERATE', 'Moderate (Clinical Monitoring Recommended)'), ('MINOR', 'Minor Interaction')], default='MAJOR', max_length=32)),
                ('clinical_mechanism', models.TextField()),
                ('management_advice', models.TextField()),
                ('evidence_source', models.CharField(default='FDA Drug Safety Database / Micromedex', max_length=255)),
            ],
            options={
                'db_table': 'hs_ai_drug_interaction_rules',
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
    ]
