# Generated by Django 5.0.6 on 2026-09-09 05:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('EMAIL', 'Email Alert'), ('SMS', 'SMS Message')], default='IN_APP', max_length=16)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine Notice'), ('IMPORTANT', 'Important Notification'), ('URGENT', 'Urgent Clinical Alert')], default='ROUTINE', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hs_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
